### ISSUE TITLE
Add Dark and Light mode toggler

### ISSUE THREAD

**Issue by rahul975337** [rahul975337/Flutter-News-App#10]
The user should be able to toggle between dark and light theme

**Comment by Balaguru4580** [comment]
I think I can implement that. Can I work on it?

**Comment by sainiteshb** [comment]
I can work on it , Can you assign me

**Comment by rahul975337** [comment]
one of you can work on setting up and other one on enhancing the same 
if you want to do it alone then too go for it ,the better one will be merged
or else if anyone of you interested in the designing part, I have some design and we need to change the UI of the app.
Do reply

**Comment by sainiteshb** [comment]
Atleast mark the other one's PR hacktoberfest-accepted , so that it will be helpful for his effort.

**Comment by rahul975337** [comment]
Sure

**Comment by rahul975337** [comment]
Also use provider or bloc to achieve the same
